# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_add',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user_add',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Add',
        ),
    ]
