# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrationapp', '0003_user_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_add',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courseapp.Course'),
        ),
        migrations.AlterField(
            model_name='user_add',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='loginregapp.Userlog'),
        ),
    ]
