# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('loginregapp', '0002_auto_20160813_1920'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userlog',
            managers=[
                ('UserManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='userlog',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
