# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregapp', '0003_auto_20160815_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='birthday',
            field=models.DateField(auto_now=True),
        ),
    ]
