# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregapp', '0004_userlog_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='birthday',
            field=models.DateField(),
        ),
    ]
